### ISSUE TITLE
Demo to add?

### ISSUE THREAD

**Issue by laoShuaiGe** [wp03052/MATRN#1]
Nice paper! Do you plan to add a demo?

**Comment by byeonghu-na** [comment]
Thanks for your interest.
You can run demo using `demo.py`, but previous uploaded code doesn't work.
Now, we update the code (d626e45), and you can use it like below:  
```
python demo.py --config configs/train_matrn.yaml --input /path/to/image --checkpoint /path/to/checkpoint
```

**Comment by laoShuaiGe** [comment]
thanks for your quick response, it's really helpful.
