### ISSUE TITLE
About Code in Line 81 of main.py 

### ISSUE THREAD

**Issue by csguoh** [wp03052/MATRN#10]
Hi!
Thanks for your great work. When I debug your code, I find Line81 and Line 82 in file `main.py` seems like they're written backwards. I have no idea whether this is correct. 
Thanks :D
https://github.com/byeonghu-na/MATRN/blob/f4d43a92555c93df67dbb8c597483e9a5c3fed14/main.py#L81
https://github.com/byeonghu-na/MATRN/blob/f4d43a92555c93df67dbb8c597483e9a5c3fed14/main.py#L82

**Comment by byeonghu-na** [comment]
Thank you for your interest.

We want to add Validation set from [Clova AI](https://github.com/clovaai/deep-text-recognition-benchmark#download-lmdb-dataset-for-traininig-and-evaluation-from-here). But, our backbone [code](http://github.com/FangShancheng/ABINet/blob/main/main.py) used `valid_ds` with test roots, and we don't want to modify it.

Actually, these lines are quite confusing, but in now the code gives same results (intermediate performances, save the best model, ...) for validation and test sets.
