### ISSUE TITLE
Predict More Characters

### ISSUE THREAD

**Issue by Mountchicken** [wp03052/MATRN#11]
Hello there!
- Great work. I'd like to ask how to train the align model with more characters. The current implementation can only recognize 36 characters (0~9, a~z). I want to recognize 90 characters (0~9, a~z, A~Z, and some symbols). 
- I tried to modify some code and now I can train on 90 characters. However, I am facing a problem that I can not load the pre-trained language model and vision model, as they are trained on 36 characters. Is there any way to modify the code so that I can load the pre-trained weights?

**Comment by yiren556** [comment]
How many epochs can you train? After I modify the epoch, it always ends after epoch9
![e0f51241df1776c05f1781607811f25](https://user-images.githubusercontent.com/99472127/199927296-638b669d-f0f8-41ab-8a51-31f45d571e6f.jpg)

**Comment by Mountchicken** [comment]
@yiren556 
I didn't modify any hyperparameters and the training ended at the 9th epoch.

**Comment by yiren556** [comment]
This is the result of my debugging, I don't understand why it stops
![9aef9b27f6f2fe65b148436d0d199d4](https://user-images.githubusercontent.com/99472127/199960077-cc17a04a-5dbd-40eb-aab5-2e4cea358f64.jpg)

**Comment by byeonghu-na** [comment]
Hi, sorry for late reply and thank you for your interest.

I think you may change `charset_path` in `template.yaml` from 'data/charset_62.text' to your own charset, and `case_sensitive` to True.

As you know, pre-trained language and vision models are trained on 36 characters. Therefore, you need to train these pre-trained models on 90 characters, or you may load these pre-trained models without the final classification layer, which is related to the size of character set.

I think this link is useful to ignore size mismatch problem. (https://github.com/Lightning-AI/lightning/issues/4690#issuecomment-731152036)
Apply this methods to loading pre-trained model, which are in below:
https://github.com/byeonghu-na/MATRN/blob/57b6b8e0bf1d707c2cde4ef3e5fe4c4fc579d445/modules/model.py#L17-L19
https://github.com/byeonghu-na/MATRN/blob/57b6b8e0bf1d707c2cde4ef3e5fe4c4fc579d445/modules/model_language.py#L39
https://github.com/byeonghu-na/MATRN/blob/57b6b8e0bf1d707c2cde4ef3e5fe4c4fc579d445/modules/model_vision.py#L39
