### ISSUE TITLE
Training always ends

### ISSUE THREAD

**Issue by yiren556** [wp03052/MATRN#12]
![d5aebaadc510b758dbc06b885fa9d7e](https://user-images.githubusercontent.com/99472127/199925518-5da984b9-5c11-44e0-ae24-5bce1628e12b.jpg)
Excuse me?
Why does the process still end when the training reaches epoch9 after the configuration file is modified

**Comment by yiren556** [comment]
![image](https://user-images.githubusercontent.com/99472127/199926660-ce25c7f2-45ab-43c2-8ed5-d83917c01776.png)
This is my modified configuration file

**Comment by byeonghu-na** [comment]
Hello, sorry for late reply.

I found that the baseline code also occurs same problem. (https://github.com/FangShancheng/ABINet/issues/11, https://github.com/FangShancheng/ABINet/issues/52, https://github.com/FangShancheng/ABINet/issues/79)

From these replies and my trial, you should change the sum of `optimizer.scheduler.periods` in the configuration file to epochs, e.g. [400, 100] for 500 epochs.

**Comment by byeonghu-na** [comment]
For convenience, I add assertion of scheduler periods and epochs. (12fd00a)
Thank you for your contribution!
