### ISSUE TITLE
Question about metrics

### ISSUE THREAD

**Issue by Lyf1122** [wp03052/MATRN#14]
Hi, when I was training vision model, I noticed several metrics which I don't understand. "ccr cwr ted ned ted/w"
![image](https://user-images.githubusercontent.com/52245778/219307406-73d8d18f-d5a7-4b58-8600-249bcc3634d4.png)
I guess the metrics are from fast-ai, but I cannot find them in the docs.
![image](https://user-images.githubusercontent.com/52245778/219308471-2035b721-4d6c-4980-9554-3483eb491c59.png)
Thank you!

**Comment by byeonghu-na** [comment]
Hello, thank you for your interest!
Basically, this part comes from our baseline code, ABINet. You can check how can we get `ast_metrics` from `TextAccuracy` class in `callback.py`.

https://github.com/byeonghu-na/MATRN/blob/219e2db5ebce690b906fb2d142d1a44e9ca819f0/callbacks.py#L198-L268

* CCR: character-level accuracy
* CWR: word-level accuracy
* TED: total edit distance (https://en.wikipedia.org/wiki/Edit_distance)
* NED: normalized edit distance
* TED/w: total edit distance / the number of words

We mainly use CWR for our metrics, and I think it is common.

Thank you.

**Comment by Lyf1122** [comment]
Thank you!
