### ISSUE TITLE
change input image size error

### ISSUE THREAD

**Issue by woans0104** [wp03052/MATRN#16]
Is it possible to learn by changing the image size? When I resized 128x32(default size) to 256x32, an error occurred.

**Comment by byeonghu-na** [comment]
Hello. Thank you for letting me know the error.

We now modify this image size error problem (https://github.com/byeonghu-na/MATRN/commit/d91ac05f43278f8e9a59252b4f9e45a457db13c2) and we check the code is now working!

**Comment by woans0104** [comment]
thanks :)
