### ISSUE TITLE
Question about evaluation on each dataset

### ISSUE THREAD

**Issue by Lyf1122** [wp03052/MATRN#17]
Thanks for your nice work.
I noticed the evaluation results on different dataset in your paper, just like this image.
![image](https://user-images.githubusercontent.com/52245778/221766457-81e3a2f8-2495-491d-8a82-a21d6b7e7914.png)
When I evaluated the dataset, I only got the total result like this instead of each dataset result:
![image](https://user-images.githubusercontent.com/52245778/221767196-fc614bc8-9a5a-4232-9527-1fc0ff080bfb.png)
I wander that how to evaluate each dataset.

Thanks!

**Comment by byeonghu-na** [comment]
Hi! Actually, you may change `dataset_test_roots` of yaml file as each dataset root.
For your convenience, you may use `test_root` argument.
https://github.com/byeonghu-na/MATRN/blob/db9e29e8261920475d011e9dd0e434031fa214bd/main.py#L217

**Comment by Lyf1122** [comment]
Thank you for your answer. The issue has been resolved.
Have a nice day.
