### ISSUE TITLE
 The calculation of accuracy prediction in evaluation dataset

### ISSUE THREAD

**Issue by Qingkali** [wp03052/MATRN#18]
Hello! I have trained the model according to your deployment, and would like to ask how to test the accuracy of IIIT5k, SVT, IC15, SVTP, CUTE and other data sets. I hope you can answer it, thank you

**Comment by byeonghu-na** [comment]
Hi, I think this question is same as #17.

You may change `dataset_test_roots` of yaml file as each dataset root.
For your convenience, you may use `test_root` argument.
https://github.com/byeonghu-na/MATRN/blob/db9e29e8261920475d011e9dd0e434031fa214bd/main.py#L217

Note that the evaluation code script is explained in README.
https://github.com/byeonghu-na/MATRN#training-and-evaluation

**Comment by Qingkali** [comment]
This is helpful for me, thanks for your answer.
