### ISSUE TITLE
作者你好，请问你论文里多模态中交叉注意力可视化在代码哪个部分

### ISSUE THREAD

**Issue by qyfff** [wp03052/MATRN#19]

**Comment by byeonghu-na** [comment]
Thank you for your interest. Could you translate your issue in English? I cannot understand Chinese.

**Comment by qyfff** [comment]
Hi author, your matrn text recognition algorithm is very good, can you teach me how to visualise the image above?


2439512017
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "byeonghu-na/MATRN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月11日(星期一) 下午3:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [byeonghu-na/MATRN] 作者你好，请问你论文里多模态中交叉注意力可视化在代码哪个部分 (Issue #19)





 
Thank you for your interest. Could you translate your issue in English? I cannot understand Chinese.

**Comment by byeonghu-na** [comment]
I cannot see the image. If the image is in our paper, you can tell me the figure number.

**Comment by qyfff** [comment]
Fig. 4. Examples of self-attention maps in multi-modal FE. Attention maps on the
top-right and the bottom-left indicate the cross attentions between two modalities.

&nbsp;


2439512017
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Byeonghu ***@***.***&gt;; 
发送时间: 2023年9月11日(星期一) 下午4:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [byeonghu-na/MATRN] 作者你好，请问你论文里多模态中交叉注意力可视化在代码哪个部分 (Issue #19)





 
I cannot see the image. If the image is in our paper, you can tell me the figure number.

**Comment by byeonghu-na** [comment]
You can extract these self-attention maps from this module.

https://github.com/byeonghu-na/MATRN/blob/dee0641ca90839daec57b92719f7e5d909e19d4d/modules/model_semantic_visual_backbone_feature.py#L97

https://github.com/byeonghu-na/MATRN/blob/dee0641ca90839daec57b92719f7e5d909e19d4d/modules/transformer.py#L789-L791

**Comment by qyfff** [comment]
Thank you very much.love you
&nbsp;


2439512017
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Byeonghu ***@***.***&gt;; 
发送时间: 2023年9月11日(星期一) 下午4:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [byeonghu-na/MATRN] 作者你好，请问你论文里多模态中交叉注意力可视化在代码哪个部分 (Issue #19)





 
You can extract this self-attention maps from this module.
 
https://github.com/byeonghu-na/MATRN/blob/dee0641ca90839daec57b92719f7e5d909e19d4d/modules/model_semantic_visual_backbone_feature.py#L97
 
https://github.com/byeonghu-na/MATRN/blob/dee0641ca90839daec57b92719f7e5d909e19d4d/modules/transformer.py#L789-L791
