### ISSUE TITLE
Question about code

### ISSUE THREAD

**Issue by Sisi0518** [wp03052/MATRN#3]
Thank you for sharing the code！

The 34-th line in modules/model_matrn_iter.py: the self.semantic_visual has no attribute about pe. 
So I get the error "torch.nn.modules.module.ModuleAttributeError: 'BaseSemanticVisual_backbone_feature' object has no attribute 'pe'"

So as the 39-th and 44-th lines.

Is there something wrong here？

**Comment by byeonghu-na** [comment]
Thank you for letting me know the error.
We modify `modules/model_matrn_iter.py` (43271d6) and we check the code is now working.
