### ISSUE TITLE
vision and language model training

### ISSUE THREAD

**Issue by bharatsubedi** [wp03052/MATRN#7]
Could you please explain how to train vision and language models for Korean and Japanese languages?

**Comment by lerndeep** [comment]
@wp03052 Following

**Comment by byeonghu-na** [comment]
Thank you for your interest. I understood your question as a way to train pre-train vision and language models.

First, you need to prepare lmdb dataset. You may use `tools` directory which comes from [clova](https://github.com/clovaai/deep-text-recognition-benchmark) and [ABINet](https://github.com/FangShancheng/ABINet). Please check instruction from [here](https://github.com/clovaai/deep-text-recognition-benchmark#when-you-need-to-train-on-your-own-dataset-or-non-latin-language-datasets).

Next, use this codes for pre-train vision and language models with modified yaml files:

(vision)
~~~
python main.py --config=configs/pretrain_vision_model.yaml
~~~
(language)
~~~
python main.py --config=configs/pretrain_language_model.yaml
~~~
You need to modify `dataset.train.roots`, `dataset.test.roots`, `dataset.valid.roots` in yaml files to your train/test/valid dataset roots.

Finally, you can train MATRN with modified yaml file (same as above, change dataset roots!)
