### ISSUE TITLE
Error about the model when using resnet as the backbone.

### ISSUE THREAD

**Issue by Zhou2019** [wp03052/MATRN#9]
Hello author, the following error occurred in the model when I used Resnet as the model backbone instead of ResTransformer. No such error occurred when I ran ABINet using ResNet as the backbone of the model.

```
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation:
 [torch.FloatTensor [10, 256, 512]], which is output 0 of ViewBackward, is at version 28; expected version 0 instead. 
Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```

I found that backbone must have transformer in your model, if there is no transformer behind CNN, there will be mistakes, but I can't find more specific reasons.
I only changed the backbone in the train_matrn.yaml configuration file.

Thanks for your reply!

**Comment by byeonghu-na** [comment]
I'm sorry for very late reply for your Issue and thank you for letting me know the error.

One of MATRN's feature is SES (spatial encoding to semantics) which is to guide the relationship between visual and semantic features. This encoding is based on the sinusoidal spatial position embedding which is used in Transformer visual backbone. Therefore, we only consider the ResTransformer backbone.

We now modify Resnet-based backbone (ResNet + position embedding) (https://github.com/byeonghu-na/MATRN/commit/ee974862b670c8904d6d44eb43afd7b01044c57d) and we check the code is now working!
